Repository Eric-Cortez/Carra, pull requests merged in 2025-01, with the labels that each got.

#9 Topic routes updates
  backend/controllers/topicController.go
  backend/controllers/usersController.go
  backend/main.go
Labels: enhancement

#10 feat: install Shaude UI for improved component library
  frontend/README.md
  frontend/components.json
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/app/login/page.tsx
  frontend/src/assets/fav-logo.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/parked-black-car.jpg
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/login-form.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/index.css
  frontend/src/lib/utils.ts
  frontend/src/logo.svg
  frontend/src/main.tsx
  frontend/src/pages/Login/index.tsx
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: enhancement

#13 Update Project README: Backend and Frontend Setup Instructions
  README.md
  backend/README.md
  frontend/README.md
Labels: documentation

#12 Set up GitHub Actions CI to run lint checks for frontend on PRs
  .github/workflows/lint.yml
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/.prettierignore
  frontend/.prettierrc.json
  frontend/components.json
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/src/App.test.tsx
  frontend/src/App.tsx
  frontend/src/app/Home/index.tsx
  frontend/src/app/NotFound/index.tsx
  frontend/src/app/createAppSlice.ts
  frontend/src/app/hooks.ts
  frontend/src/app/login/page.tsx
  frontend/src/app/store.ts
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/PrivateRoute/index.tsx
  frontend/src/components/login-form.tsx
  frontend/src/components/mode-toggle.tsx
  frontend/src/components/theme-provider.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/navigation-menu.tsx
  frontend/src/components/ui/separator.tsx
  frontend/src/constants/statusCodes.ts
  frontend/src/features/auth/authAPI.ts
  frontend/src/features/auth/authSlice.ts
  frontend/src/features/counter/Counter.tsx
  frontend/src/features/counter/counterAPI.ts
  frontend/src/features/counter/counterSlice.test.ts
  frontend/src/features/counter/counterSlice.ts
  frontend/src/features/quotes/Quotes.tsx
  frontend/src/features/quotes/quotesApiSlice.ts
  frontend/src/index.css
  frontend/src/lib/utils.ts
  frontend/src/main.tsx
  frontend/src/setupTests.ts
  frontend/src/utils/test-utils.tsx
  frontend/tsconfig.json
Labels: enhancement

#17 [client] feat: Enhance Navigation and Layout with ShadCN Components
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/app/Home/index.tsx
  frontend/src/app/Users/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/ui/avatar.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/form.tsx
  frontend/src/components/ui/resizable.tsx
  frontend/src/constants/baseUrl.ts
  frontend/src/features/auth/authAPI.ts
Labels: enhancement

#19 Ericcortez/frontend/home page style
  .vscode/settings.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/Home/index.tsx
  frontend/src/app/login/page.tsx
  frontend/src/components/Forms/login-form.tsx
  frontend/src/components/Forms/question-form.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/components/account-dropdown.tsx
  frontend/src/components/ui/navigation-menu.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/skeleton.tsx
  frontend/src/components/ui/textarea.tsx
  frontend/src/features/auth/authAPI.ts
  frontend/src/features/auth/authSlice.ts
Labels: enhancement

#21 resolved broken link added TODO for where this will go later
  frontend/src/app/login/page.tsx
Labels: bug

#20 Adds Ken to Contributors list
  README.md
Labels: documentation
